language: node_js
node_js:
- 15
before_install:
  - npm install -g codecov
deploy:
  provider: npm
  email: "$EMAIL"
  api_key: "$API_TOKEN"
  on:
    tags: true
    repo: anaue/qitech
    branch: main
  skip_cleanup: 'true'
